# Generated by Django 4.2.11 on 2024-04-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Способ доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_place',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Место самовывоза'),
        ),
    ]
