# Generated by Django 4.2.11 on 2024-07-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('Яндекс доставка', 'Яндекс доставка'), ('Почта', 'Почта')], max_length=250, null=True, verbose_name='Способ доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_place',
            field=models.CharField(blank=True, choices=[('«Посольство Уральских гор»', '«Посольство Уральских гор»'), ('«Территория странствий»', '«Территория странствий»'), ('«Центр путешественников»', '«Центр путешественников»'), ('Клуб СГС', 'Клуб СГС'), ('Магазин SportX', 'Магазин SportX'), ('Пермский спелеоклуб', 'Пермский спелеоклуб'), ('«Земля приключений»', '«Земля приключений»'), ('«Вертикаль»', '«Вертикаль»'), ('«Геккон»', '«Геккон»')], max_length=250, null=True, verbose_name='Пункт самовывоза'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('На доставке', 'На доставке'), ('Завершен', 'Завершен')], default='В обработке', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
