# Generated by Django 4.2.11 on 2024-07-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='send_to_email',
            field=models.BooleanField(default=False, verbose_name='Выслать на электронную почту'),
        ),
    ]
