# Generated by Django 4.2.11 on 2024-07-07 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_send_to_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='send_to_email',
        ),
    ]
