# Generated by Django 4.2.11 on 2024-05-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_type_order_pickup_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_place',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Пункт самовывоза'),
        ),
    ]
