# Generated by Django 4.2.11 on 2024-07-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_send_to_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='send_to_email',
            field=models.BooleanField(default=False, verbose_name='Выслать на электронную почту'),
        ),
    ]
