# Generated by Django 4.2.11 on 2024-08-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_send_to_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='send_to_email',
            field=models.BooleanField(default=False, verbose_name='Выслать на электронную почту'),
        ),
    ]
