# Generated by Django 4.2.11 on 2024-04-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение 2'),
        ),
    ]
