# Generated by Django 4.2.11 on 2024-04-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_products_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение 3'),
        ),
    ]
