# Generated by Django 4.2.11 on 2024-08-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_products_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение 4'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение 5'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение 6'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение 7'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение 8'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение 9'),
        ),
    ]
